backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "/src/pages/blog/img"
public_folder: "img"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

collections:
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About" # Used in the UI
    folder: "src/pages/about" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
      - {label: "Path", name: "path", widget: "hidden", default: "/about"}
      - {label: "Title", name: "title", widget: "string"}
